import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Swiper, SwiperSlide} from 'swiper/react'
// Core modules imports are same as usual
import { Autoplay, EffectCube, Navigation, Pagination } from 'swiper';
// Direct React component imports


// Styles must use direct files imports
import 'swiper/css'; // core Swiper
const inter = Inter({ subsets: ['latin'] })
// import 'swiper/swiper.scss'
// import "";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Swiper
        direction='horizontal'
        loop={true}
        // effect={"cube"}
        // cubeEffect={{
        //   shadow: true,
        //   slideShadows: true,
        //   shadowOffset: 20,
        //   shadowScale: 0.94,
        // }}
        slidesPerView={3}
        spaceBetween={0}
        autoplay={true}
        modules={[Autoplay,EffectCube]}
        style={{width:'150px',height:"50px"}}
        >
          <SwiperSlide style={{}}>
            <Image src="https://swiperjs.com/demos/images/nature-1.jpg" width={50} height={50} alt='' />
          </SwiperSlide>
          <SwiperSlide style={{}}>
            <Image src="https://swiperjs.com/demos/images/nature-2.jpg" width={50} height={50} alt='' />
          </SwiperSlide>
          <SwiperSlide style={{}}>
            <Image src="https://swiperjs.com/demos/images/nature-3.jpg" width={50} height={50} alt='' />
          </SwiperSlide>
          {/* <SwiperSlide style={{}}>
            <Image src="https://swiperjs.com/demos/images/nature-1.jpg" width={50} height={50} alt='' />
          </SwiperSlide>
          <SwiperSlide style={{width:'0vw'}}>
            <Image src="https://swiperjs.com/demos/images/nature-2.jpg" width={50} height={50} alt='' />
          </SwiperSlide>
          <SwiperSlide style={{}}>
            <Image src="https://swiperjs.com/demos/images/nature-3.jpg" width={50} height={50} alt='' />
          </SwiperSlide> */}
 
        </Swiper>
      </main>
    </>
  )
}
